version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net

  api:
    build: ./api
    container_name: api_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PASSWORD: pass
    depends_on:
      - db
    networks:
      - app_net

  frontend:
    image: nginx:latest
    container_name: frontend_web
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api
    networks:
      - app_net

volumes:
  pgdata:

networks:
  app_net:
