# Imagem simples (sem multi-stage)
FROM node:18

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o package.json e instala dependências
COPY package.json ./
RUN npm install

# Copia o restante do código
COPY . .

# Expõe a porta da aplicação
EXPOSE 3000

# Comando para iniciar o app
CMD ["npm", "start"]
