services:
  api:
    build: ./api
    container_name: api_app
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api"]
      interval: 10s
      timeout: 5s
      retries: 3
